spring.application.name=Spokify-Back
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=Spokify

server.port=4000

logging.level.org.springframework.data=debug
logging.level.=error

spring.data.mongodb.auto-index-creation=true

TOKEN_SIGNATURE=${JWT_SECRET_KEY}

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# إعدادات الـ SMTP لسيرفر Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_EMAIL_USER}
# الباسورد الـ 16 حرف اللي أنت استخرجته (بدون مسافات)
spring.mail.password=${MY_EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# إعداد إضافي للتأكد من ترميز الحروف العربية لو هتبعت إيميلات بالعربي
spring.mail.default-encoding=UTF-8

